version: '3'
services:
    broker:
        build: ./broker
        ports:
        - "1883:1883"

    img_handler:
        build: ./img_handler
        privileged: true
        depends_on: 
        - broker
